version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/solidus
    environment:
      - DB_HOST=db
      - DB_NAME=solidus-demo_development
      - DB_NAME_TEST=solidus-demo_test
      - DB_PASSWORD=solidus-demo
      - DB_PORT=5432
      - DB_USER=solidus-demo
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=solidus-demo_development
      - POSTGRES_PASSWORD=solidus-demo
      - POSTGRES_USER=solidus-demo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
